With src_data as (
SELECT DISTINCT LOCATION_ISO_CODE, TOTAL_REGENCIES, TOTAL_CITIES, TOTAL_DISTRICTS, TOTAL_URBAN_VILLAGES, TOTAL_RURAL_VILLAGES, AREA_KM_2_, POPULATION, POPULATION_DENSITY
from {{ source('Snowflake_FIVETRAN_INTERVIEW_DB', 'COVID_19_INDONESIA_NISHANT_KUMAR') }}
),

final as (
    select * from src_data
)
select * from final